### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by rsperlich** [BOC-Group/developer-examples#15]
### FILE_POINTER Attribute editable
Hi there!
I am currently trying to use your API and did not find a way to edit FILEPOINTER Attributes.
For this path: /rest/3.0/repos/{repo_id}/objects/{object_id}
In the documentation it says that the value can only be one of string ,number($double),integer, boolean.

Does this mean that there is no way to edit pointer attributes. I tried some ways such as:
```
{
  "attributes": [
    {
      "metaName": "REFERENCED_DOCUMENT",
      "value": {
                    "parameter" = "path/to/file",
                    "program" = ""
       }
    }
  ]
}
```
Is there apossibility to edit these kind of attributes or is it only possible for the given ones?

**Comment by mathiaswinklhofer** [comment]
Hi,
It is possible to edit this attribute. The body you sent is almost correct.
Try this instead:

`{
  "attributes": [
    {
      "metaName": "REFERENCED_DOCUMENT",
      "value": 
      {
        "parameter":"https://www.boc-group.com/"
      }
    }
  ]
}`

**Comment by rsperlich** [comment]
Worked! Thank you
