### ISSUE TITLE
[Question] Creating new relation between process and document

### ISSUE THREAD

**Issue by rsperlich** [BOC-Group/developer-examples#16]
**Creating New Relation Between Two Repository Objects (One Document and One Process, via RC_REFERENCED_DOCUMENTS)**

Greetings,

I am currently working on implementing your API to establish a connection between processes and existing documents. However, I encountered an issue while using the endpoint:

`/rest/3.0/repos/{repo_id}/objects/{object_id}/relations/{direction}/{rel_name}`

My intention is to create an outgoing relation through RC_REFERENCED_DOCUMENTS. I initially followed your example with the following parameters:

`/rest/3.0/repos/{repo_id}/objects/{object_id_process}/relations/outgoing/RC_REFERENCED_DOCUMENTS`

The body was set as:

`{"toId": "{id_of_document}"}`

Upon executing this, I received a 404 Error with the error message "(Not found) Source or target artifact is not existing, or relation of the given class is not defined between those artifacts." I believe the issue lies in the relation class not being defined, as the objects appear to exist.

To troubleshoot, I attempted the same process with an existing relation (manually created). Using the same setup for the request, but now for a relation that already exists in RC_REFERENCED_DOCUMENTS, resulted in a 409 error, indicating that the API recognizes the relation.

Afterwards, I created two processes (A, B) and linked them to documents (A, B). Process A was linked to document A, and process B to document B. Attempting to create a relation between these pairs resulted in 409 errors. Interestingly, when attempting to create a relation between process A and document B, a 404 error was generated.

I am uncertain whether the issue lies in my project setup or if there is something I am overlooking in the process of creating the relation. Could you provide insights or guidance on resolving this matter?

Thank you and Happy Holidays!

**Comment by mathiaswinklhofer** [comment]
Hi,

I just tried to reproduce this behavior, but for me the creation worked fine and resulted in a 201 status code and the relation being visible in the client.
Could it be that the user that you are doing the REST call with does not have access to either the process or the document? 
Also, which exact version of ADONIS are you using?

Best Regards!

**Comment by rsperlich** [comment]
Hi,
thank you for your answer.
I am using V14.1.13.
Would I be able to do get requests to the document and process if I did not have access? Because the get requests to the individual objects work fine.

Kind Regards!

**Comment by mathiaswinklhofer** [comment]
No, if your user does not have read access, you would also get a 404 when accessing the details of the individual objects.
Regarding the call that you made, does your request look like this (screenshot from Postman)?
![image](https://github.com/BOC-Group/developer-examples/assets/996422/8e177cfb-995d-40a1-be61-9ae2d40bd2d8)

If not, we can take a look at the log files. What kind of account are you using, are you working on an on premise version of ADONIS, or a hosted (SaaS) version?

**Comment by rsperlich** [comment]
Hi, the request body looks the same, I will need to check with the admin on the questions regarding adonis. Will update you once I have more info.

Many Thanks!

**Comment by rsperlich** [comment]
Happy new Year!  It was an issue regarding write rights in adonis through the api user. Thanks for the help !
