### ISSUE TITLE
[Question] Relation between repository_objects and models

### ISSUE THREAD

**Issue by rsperlich** [BOC-Group/developer-examples#18]
Hi, 

I have a question regarding the possibility of linking repository objects, such as C_DOCUMENTS, to a model.

I attempted to achieve this using the API function /rest/3.0/repos/{repo_id}/objects/{object_id}/relations/{direction}/{rel_name}, but encountered a 404 Error. I'm wondering if it's feasible to use a model object ID in the object_id parameter for this operation.

My suspicion is that the issue might be related to the fact that the model is treated differently from a repository_object or that the api user does not have access on the folder. Could you help me with this matter?

I've also successfully performed GET requests on both the model and the object.

I would greatly appreciate any assistance you could provide on this matter.

Thank you in advance & kind regards

**Comment by mathiaswinklhofer** [comment]
Hi,

Unfortunately, at the moment, the API only allows to create such relations from repository objects to repository objects or modelling objects, but not to models directly. Also relations from models to objects can currently not be created via the REST API. 

Best Regards

**Comment by rsperlich** [comment]
Thank you very much for the info.
