### ISSUE TITLE
[Bug] https://adonis-ce.boc-cloud.com/main.view#0

### ISSUE THREAD

**Issue by Spicules** [BOC-Group/developer-examples#7]
**Describe the bug**

Tutorial Modellieren hängt direkt am Anfang: 
Das Fenster "Klicken Sie auf den Button, um Inhalte zu erstellen" geht nicht weg, egal wie oft ich auf den Button + Neu klicke.
Ich habe diese einige Sekunden probiert und dann dieses Issue Ticket aufgemacht. 

Während ich das Ticket schreibe, geht es weiter im Fenster: https://adonis-ce.boc-cloud.com/main.view#0

Der Fehler geht weg. Ist halt irritierend am Anfang. Ggfs. baut er noch etwas auf, während das Tutorial startet.

**Expected behavior**

The Tutorial continues by clicking on the Button + Neu

**To Reproduce**
Please enter here your code snippet that was used to do the request.

**Additional information**
* Product (ADONIS, ADOIT)
* Affected product version (can be found e.g. on login screen)
* Log files (e.g. SIP, Web server logs folder: \logs)
* Reproduction data (library, SIP, the "RESTAuthorization" xml file from WEB-INF/registry/rest) or at least the REST component settings (if the other files are too big)

**Comment by lukas-ramach-BOC-Group** [comment]
@Spicules : Danke für den Bug Report!
Wir können das reproduzieren und es dürfte sich tatsächlich um ein timing problem handeln. 
Wir werden uns das im Detail anschauen.
